---
other-contexts:
  - docker:ofbuild/fedora-29-qt5
  - docker:ofbuild/ubuntu:19.04
  - docker:ofbuild/fedora-root:30

all-contexts: &all-contexts
- docker:ofbuild/fedora-28-qt5
- docker:ofbuild/ubuntu-18.04-qt5
- docker:ofbuild/ubuntu-19.10-qt5
  

setups:
  - LOCAL-TEST: &LOCAL-TEST
      build-type: test
      build-jobs: 10
      openfluid-repos: OpenFLUID/openfluid
      contexts: 
        - local

  - FULL-PACK: &FULL-PACK
      build-type: package
      run-examples: "*"
      contexts: *all-contexts
      build-jobs: 12
      pyopenfluid-repos: default
      ropenfluid-repos: default
      openfluidjs-repos: default


active-setups:
- *LOCAL-TEST
...
